import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={clsx(
					poppins.className,
					"dark:bg-bg-dark dark:text-text-dark ",
					"bg-bg-light text-text-light",
					"max-w-xs ml-auto mr-auto"
				)}
			>
				{children}
			</body>
		</html>
	);
}
