import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "dark:bg-bg-dark dark:text-text-dark ",
          "bg-bg-light text-text-light",
          "max-w-xs lg:max-w-4xl ml-auto mr-auto"
        )}
      >
        {children}
      </body>
    </html>
  );
}
